name: tests

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

#    - uses: actions-rs/toolchain@v1
#      with:
#        toolchain: stable
#        override: true
#        profile: minimal

#    - uses: ilammy/msvc-dev-cmd@v1
#    - name: c
#      run: |
#        cl test.c
#        dir
#        ./test.exe
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
      env:
        RUST_LOG: trace
        RUST_BACKTRACE: '1'
    - name: Tests
      uses: actions-rs/cargo@v1
      with:
        command: test
      env:
        RUST_LOG: trace
        RUST_BACKTRACE: '1'
# vim: set ts=2 sts=2 sw=2:
