name: tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  schedule:
    - cron: '20 9 * * 1'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
        components: rustfmt, clippy

    - name: Check format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

    - name: Annotate commit with clippy warnings
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features

    - name: Security audit
      uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
      env:
        RUST_LOG: trace
        RUST_BACKTRACE: '1'
    - name: Tests
      uses: actions-rs/cargo@v1
      with:
        command: test
      env:
        RUST_LOG: trace
        RUST_BACKTRACE: '1'

# Currently does not work on Windows
#  cov:
#    runs-on: windows-latest
#    defaults:
#      run:
#        shell: bash
#    steps:
#    - uses: actions/checkout@v2
#    - uses: actions-rs/toolchain@v1
#      with:
#        toolchain: nightly
#        override: true
#        profile: minimal
#        components: llvm-tools-preview
#    - name: Install cargo-llvm-cov
#      uses: actions-rs/cargo@v1
#      with:
#        command: install
#        args: cargo-llvm-cov --version 0.1.0-alpha.4
#    - name: Generate code coverage
#      uses: actions-rs/cargo@v1
#      with:
#        command: llvm-cov
#        args: --all-features --lcov --output-path lcov.info
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v1
#      with:
#        files: lcov.info
# vim: set ts=2 sts=2 sw=2:
